For the second review
VitrivDolkom/mobileCalculator pull request #2
Opened 2023-03-03 07:36 UTC by VitrivDolkom

- Убрал проценты в ширине и высоте кнопок, убрал проценты в высоту блоков.
- использовал liveData
- слушатели событий убрал из стилей и повесил их на кнопки по айдишнику
- Flow заменил на chain

2023-03-10 12:29 UTC, Chantreck requested changes

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/res/values/styles.xml
>      <style name="CalculatorButtonStyle.Red">
Не очень удачно в данном случае использовать цвет в названии стиля, поскольку цвет может поменяться (вдруг динамические темы сделаешь), а название стиля менять не хотелось бы. Лучше отражать суть стиля - например, стиль для _акцентной_ кнопки

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
>      private lateinit var binding: ActivityMainBinding
Использование lateinit имеет некоторые недостатки, поэтому лучше его использовать в крайних случаях. В данном случае можно спокойно написать без его использования:
```kotlin
private val binding by lazy { ActivityMainBinding.inflate(layoutInflater) }
private val viewModel by viewModels<MainActivityViewModel>()
```
Благодаря `lazy` байдинг проинициализируется лениво в `onCreate` при первом обращении, а про `viewModels` можно прочитать [здесь](https://vtsen.hashnode.dev/recommended-ways-to-create-viewmodel-or-androidviewmodel#heading-by-viewmodels-activityviewmodels)

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        viewModel.currentExpression.observe(this, Observer {
В котлине, если последний аргумент функции представляет из себя лямбду, то можно записать красивее:
```kotlin
function(args) {
//код лямбды
}
```
Поэтому ты можешь записать немного красивее:
```kotlin
viewModel.currentExpression.observe(this) {
//код обсервера
}
```

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            if (it.toString() == "Error") {
Сравнивать по строкам не очень круто, поэтому можно либо создать дополнительную LiveData isError, либо можно сделать простой data class с UiState: 
```kotlin
data class UiState(
    val expression: String,
    val isError: Boolean,
)
```
Тогда в LiveData можно будет положить этот дата-класс, в данном случае оба варианта вполне равнозначны применимы на мой взгляд

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                viewModel.expression += button.text
Не стоит рассчитывать на текст на кнопке, вдруг на кнопке с нулем окажется какая-то порнография. Можно либо создать словарь, где ключ - это кнопка (`binding`), а значение - строка, а лучше значение `enum`, в котором у тебя будут лежать все кнопки. Например:
```kotlin
enum class Operation(val symbol: Char) {
ZERO('0'), ONE('1'), ..., PLUS('+')
}

val buttons= mapOf(
binding.buttons.buttonZero to Operation.ZERO,
binding.buttons.buttonOne to Operation.ONE,
...
binding.buttons.buttonPlus to Operation.PLUS,
)

buttons.forEach { button, action ->
    button.setOnClickListener {
        viewModel.action(action)
    }
}
```
В этом случае у нас у всех кнопок будет одинаковый слушатель, а во `viewModel` на основе значения `Operation` ты можешь выбирать нужную функцию. А чтобы получить знак, можно будет просто вызвать `operation.symbol`

К тому же лучше не делать присваивания `expression` и `currentExpression` из активити, следует вызывать какой-то метод `viewModel`, а она уже сама присвоит что нужно

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivityViewModel.kt
> +class MainActivityViewModel : ViewModel() {
Какая-то подозрительно маленькая у тебя `ViewModel`, обычно она обрабатывает нажатия на кнопки. Скорее всего, почти весь код из слушателей в активити должен быть здесь)

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/MainActivityViewModel.kt
> +    }
При работе с LiveData обычно пишут следующее:
```kotlin
private val _currentExpression = MutableLiveData<String>()
val currentExpression: LiveData<String> get() = _currentExpression
```
Таким образом, изменять значение мы можем только из `ViewModel`, а активити может просто наблюдать за значением

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/CalculateExpression.kt
Из-за того, что у тебя уже был код запушен в этом классе, даже нормально прокомментировать не могу)
Функция isActionInExpression какая-то очень странная и потенциально максимально не оптимальная. Как минимум можно записать так:
```kotlin
private fun isActionInExpression(expression: String): Boolean {
    return expression.any(char -> char in availActions)
}
```
А вообще лучше использовать регулярное выражение тогда уж, либо не хранить выражение как единое целое, а отдельно хранить операнды и операцию (можно в виде Operation из предыдущего комментария)

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/CalculateExpression.kt
>          when (actionSymbol.toString()) {
Хранение операции отдельно в виде Operation сильно поможет здесь, потому что позволит избавиться от сравнения строк, которое не очень оптимально. К тому же вместо строки, у которой может быть абсолютно любое значение, when будет проходиться по ограниченному числу возможных входных значений

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/CalculateExpression.kt
> +        if (newSymbol in tabooActions || (expressionText == "" && newSymbol in availActions) || (expressionText == "Error" && newSymbol in availActions)) {
Константы нужно выносить в companion object непосредственно в константы

2023-03-10 12:29 UTC, Chantreck commented on app/src/main/java/com/example/calculator/CalculateExpression.kt
Если не сложно, в следующий раз создай новый класс с этим кодом, а то я комментировать могу только изменения, которых не так много по сравнению с уже запушенной версией))

2023-03-11 08:22 UTC, VitrivDolkom commented on app/src/main/java/com/example/calculator/CalculateExpression.kt
Если отдельно хранить операнды и операцию, то где это лучше делать? В `LiveData` из `ViewModel` хранится всё целиком, мне добавить еще переменные для операции и операндов?

2023-03-11 08:57 UTC, VitrivDolkom commented on app/src/main/java/com/example/calculator/CalculateExpression.kt
А хотя это лучше хранить в `CalculateExpression` наверное

2023-03-21 11:38 UTC, closed without merging